import bcrypt from "bcryptjs";

const Data = {
  users: [
    {
      name: "Basir",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 20,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "adidas Slim Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 320,
      countInStock: 10,
      brand: "adidas",
      rating: 4.8,
      numReviews: 20,
      description: "high quality shirt",
    },
    {
      name: "Lacost Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 80,
      countInStock: 0,
      brand: "Lacost",
      rating: 4.2,
      numReviews: 90,
      description: "Normal quality product",
    },
    {
      name: "salamon Shirt",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 90,
      brand: "Salamon",
      rating: 3.5,
      numReviews: 80,
      description: "cheep product",
    },
    {
      name: "Nike pant",
      category: "pant",
      image: "/images/p5.jpg",
      price: 120,
      countInStock: 80,
      brand: "Nike",
      rating: 4.7,
      numReviews: 18,
      description: "high quality product",
    },
    {
      name: "dandg cote",
      category: "Cote",
      image: "/images/p6.jpg",
      price: 120,
      countInStock: 2,
      brand: "DANDG",
      rating: 3.5,
      numReviews: 40,
      description: "high quality Cote",
    },
  ],
};
export default Data;
